version: "2"
services:
  clothing-model:
          image: "zoomcamp-10-model:exception"
  gateway:
    image: "zoomcamp-10-gateway:002"
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"
